<?php

declare(strict_types=1);

namespace Hochwarth;

use ProcessWire\HookEvent;
use ProcessWire\Module;
use ProcessWire\WireData;
use ProcessWire\WireException;

class AccessibilityTools extends WireData implements Module
{
    public function showTools(): bool
    {
        $conf = $this->modules->getConfig($this);

        return !$this->config->admin && !$this->config->ajax && !empty($conf) && !empty($conf['enabled']) && $conf['enabled'];
    }

    /**
     * Get module information
     */
    public static function getModuleInfo(): array
    {
        return [
            'title' => 'Accessibility Tools',
            'version' => '1.0.0',
            'summary' => 'Fügt der Website ein konfigurierbares Set an Barrierefreiheits-Funktionen für Besucher hinzu.',
            'href' => 'https://github.com/pixeldasher/AccessibilityTools',
            'author' => 'Phillip "pixeldasher" Issner',
            'singular' => true,
            'permission' => 'site-accessibility',
            'icon' => 'universal-access',
            'autoload' => 'template!=admin',
            'requires' => [
                'PHP>=8.3',
                'ProcessWire>=3.0.249'
            ],
        ];
    }

    public function init(): void
    {
        $this->addHookAfter('Page::render', $this, 'injectTools');
    }

    public function ready(): void
    {
        if ($this->showTools()) {
            $moduleUrl = $this->config->urls($this);
            $this->config->scripts->add($moduleUrl . 'scripts/main.js');
            $this->config->styles->add($moduleUrl . 'styles/main.css');
        }
    }

    public function injectTools(HookEvent $event): void
    {
        if (!$this->showTools()) {
            return;
        }

        $easyLanguagePage = $this->pages->get((int) $this->get('easy_language_page'));
        $signLanguagePage = $this->pages->get((int) $this->get('sign_language_page'));

        $viewData = [
            'enableContrastMode' => (bool) $this->get('enable_contrast_mode'),
            'enableFontSizeAdjust' => (bool) $this->get('enable_font_size_adjust'),
            'easyLanguageUrl' => $easyLanguagePage->id ? $easyLanguagePage->url : '',
            'signLanguageUrl' => $signLanguagePage->id ? $signLanguagePage->url : '',
        ];

        $viewFile = $this->config->paths($this) . 'views/dialog.php';

        if (!@is_file($viewFile)) {
            if ($this->config->debug) {
                throw new WireException("Ansichtsdatei nicht gefunden unter: $viewFile");
            }

            return;
        }

        $pattern = '/<body[^>]*>/i';
        $html = $this->files->render($viewFile, $viewData);

        // Append the HTML to the body tag
        $event->return = preg_replace($pattern, "\$0{$html}", $event->return);
    }
}
